apiVersion: v1
kind: Service
metadata:
  name: searchengine-service
spec:
  selector:
    app: searchengine
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: searchengine
spec:
  selector:
    matchLabels:
      app: searchengine
  replicas: 4
  template:
    metadata:
      labels:
        app: searchengine
    spec:
      containers:
      - name: searchengine
        image: searchengine
        imagePullPolicy: Never
        ports:
        - containerPort: 5000